name: MapParser
version: 1.0
api-version: '1.20'
main: net.plexverse.mapparser.MapParser
commands:
  parse:
    description: Parses a world for datapoints.
  kitcreator:
    description: Opens a menu to create a kit using your inventory contents.